from typing import Iterable, Protocol


class TextGeneratorProtocol(Protocol):
    async def get_sentence_from_keyword(self, keyword: str, format: bool = True) -> str | None: ...
    async def get_sentence_from_two_keywords( self, primary_word: str, secondary_word: str, format: bool = True) -> str | None: ...
    async def get_text_from_keywords(self, keywords: Iterable[str]) -> str | None: ...