version: "3.8"
services:

  db:
    image: postgres
    container_name: tgbot_pgdb_container
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 80s
    volumes:
      - fastbot-pgdb-data:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: tg_bot_pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    env_file:
      - .env
    volumes:
      - fastbot-pgadmin-data:/var/lib/pgadmin
    depends_on:
      db:
        condition: service_healthy

volumes:
  fastbot-pgadmin-data:
  fastbot-pgdb-data: