FROM python:3.11-slim

WORKDIR /code

ENV PYTHONFAULTHANDLER=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONHASHSEED=random
ENV PYTHONDONTWRITEBYTECODE=1

COPY --from=requirements-stage /tmp/requirements.txt /code/requirements.txt

RUN pip install --no-compile --no-cache-dir --upgrade -r /code/requirements.txt

COPY . /code

EXPOSE 8000

ENV MODE="TEST"

CMD alembic upgrade head; pytest -v -s -W ignore::DeprecationWarning