FROM python:3.11-slim as requirements-stage
WORKDIR /tmp
RUN pip install poetry-plugin-export
COPY ./pyproject.toml ./poetry.lock* /tmp/
RUN poetry export -f requirements.txt --output requirements.txt --without-hashes --with dev,test


FROM python:3.11-slim

WORKDIR /code

ENV PYTHONFAULTHANDLER=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONHASHSEED=random
ENV PYTHONDONTWRITEBYTECODE=1

COPY --from=requirements-stage /tmp/requirements.txt /code/requirements.txt

RUN pip install --no-compile --no-cache-dir --upgrade -r /code/requirements.txt

COPY . /code

EXPOSE 8000

ENV MODE="DEV"

CMD alembic upgrade head; uvicorn app.main:app --reload --host 0.0.0.0 --port 8000