from g4f import Provider


providers = [
    # Provider.AI365VIP,
    Provider.Allyfy,
    Provider.AiChatOnline,
    Provider.AiChats,
    Provider.Airforce,
    # Provider.Aura,
    # Provider.Bing,
    # Provider.BingCreateImages,
    # Provider.Binjie,
    Provider.Bixin123,
    Provider.Blackbox,
    Provider.ChatGot,
    # Provider.Chatgpt4Online,
    # Provider.Chatgpt4o,
    Provider.ChatgptFree,
    # Provider.CodeNews,
    Provider.DDG,
    # Provider.DeepInfra,
    # Provider.DeepInfraImage,
    # Provider.FlowGpt,
    # Provider.Free2GPT,
    Provider.FreeChatgpt,
    # Provider.FreeGpt,
    # Provider.FreeNetfly,
    # Provider.GeminiPro,
    # Provider.GigaChat,
    # Provider.GptTalkRu,
    Provider.HuggingChat,
    # Provider.HuggingFace,
    # Provider.Koala,
    # Provider.Liaobots,
    # Provider.LiteIcoding,
    # Provider.Local,
    # Provider.MagickPen,
    # Provider.MetaAI,
    # Provider.MetaAIAccount,
    Provider.Nexra,
    # Provider.Ollama,
    # Provider.PerplexityLabs,
    # Provider.Pi,
    Provider.Pizzagpt,
    # Provider.Prodia,
    # Provider.Reka,
    # Provider.Snova,
    # Provider.Replicate,
    Provider.ReplicateHome,
    Provider.TeachAnything,
    Provider.TwitterBio,
    Provider.Upstage,
    # Provider.Vercel,
    # Provider.WhiteRabbitNeo,
    Provider.You,
]
