"""empty message

Revision ID: b4e48086e674
Revises: 1ca7276a8283
Create Date: 2023-12-22 15:21:13.499634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4e48086e674'
down_revision: Union[str, None] = '1ca7276a8283'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_tg_id', table_name='users')
    op.drop_column('users', 'tg_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tg_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_index('ix_users_tg_id', 'users', ['tg_id'], unique=False)
    # ### end Alembic commands ###
