"""empty message

Revision ID: 42c773427fde
Revises: 48aa33e760af
Create Date: 2023-11-19 16:36:37.389149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42c773427fde'
down_revision: Union[str, None] = '48aa33e760af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('language_pairs_vocabulary_id_fkey', 'language_pairs', type_='foreignkey')
    op.create_foreign_key(None, 'language_pairs', 'vocabulary_sets', ['vocabulary_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'language_pairs', type_='foreignkey')
    op.create_foreign_key('language_pairs_vocabulary_id_fkey', 'language_pairs', 'vocabulary_sets', ['vocabulary_id'], ['id'])
    # ### end Alembic commands ###
