"""empty message

Revision ID: fa05e3a728b4
Revises: 01d981efa3d1
Create Date: 2023-11-16 21:30:12.755244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa05e3a728b4'
down_revision: Union[str, None] = '01d981efa3d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word_pairs')
    op.drop_table('vocabulary_bundles')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vocabulary_bundles',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('vocabulary_bundles_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='vocabulary_bundles_owner_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='vocabulary_bundles_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('word_pairs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('bundle_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('word', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('translation', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['bundle_id'], ['vocabulary_bundles.id'], name='word_pairs_bundle_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='word_pairs_pkey')
    )
    # ### end Alembic commands ###
