name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      test-db:
        image: postgres:15.6-alpine
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: sudo apt-get install docker-compose -y

      - name: Create .test.env file from secret
        run: echo "${{ secrets.TEST_ENV_FILE_CONTENT }}" > ./secrets/environment/.test.env

      - name: Build Docker container for tests
        run: docker build -f Dockerfile.test -t my-app:test .

      - name: Run tests
        run: docker run --network=${{ job.services.test-db.network }} my-app:test
